# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_ui(object):
    def setupUi(self, login_ui):
        login_ui.setObjectName("login_ui")
        login_ui.resize(910, 570)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(login_ui.sizePolicy().hasHeightForWidth())
        login_ui.setSizePolicy(sizePolicy)
        login_ui.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(login_ui)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(login_ui)
        self.frame_2.setStyleSheet("\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(260, 50, 391, 481))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(40, 40, 329, 78))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(19)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setObjectName("label_5")
        self.user_name_lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.user_name_lineEdit_3.setEnabled(True)
        self.user_name_lineEdit_3.setGeometry(QtCore.QRect(110, 140, 190, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(122)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_name_lineEdit_3.sizePolicy().hasHeightForWidth())
        self.user_name_lineEdit_3.setSizePolicy(sizePolicy)
        self.user_name_lineEdit_3.setMinimumSize(QtCore.QSize(190, 40))
        self.user_name_lineEdit_3.setMaximumSize(QtCore.QSize(190, 40))
        self.user_name_lineEdit_3.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(15)
        self.user_name_lineEdit_3.setFont(font)
        self.user_name_lineEdit_3.setStyleSheet("\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.user_name_lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.user_name_lineEdit_3.setObjectName("user_name_lineEdit_3")
        self.password_lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.password_lineEdit_3.setGeometry(QtCore.QRect(110, 210, 190, 40))
        self.password_lineEdit_3.setMinimumSize(QtCore.QSize(190, 40))
        self.password_lineEdit_3.setMaximumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(15)
        self.password_lineEdit_3.setFont(font)
        self.password_lineEdit_3.setStyleSheet(";\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.password_lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit_3.setObjectName("password_lineEdit_3")
        self.login_pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.login_pushButton_2.setGeometry(QtCore.QRect(110, 280, 190, 40))
        self.login_pushButton_2.setMinimumSize(QtCore.QSize(190, 40))
        self.login_pushButton_2.setMaximumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.login_pushButton_2.setFont(font)
        self.login_pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_pushButton_2.setStyleSheet("background-color: :rgba(0,0,0,240);")
        self.login_pushButton_2.setObjectName("login_pushButton_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 911, 581))
        self.frame_3.setStyleSheet("background-color: rgba(0, 85, 100,150);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(780, 20, 120, 80))
        self.frame_4.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 10, 50, 50))
        self.pushButton_2.setStyleSheet("border-image: url(:/icon/icon/删除菜单.svg);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setGeometry(QtCore.QRect(60, 10, 50, 50))
        self.pushButton.setStyleSheet(";\n"
"border-image: url(:/icon/icon/关闭弹窗.svg);")
        self.pushButton.setText("")
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.frame_3.raise_()
        self.frame.raise_()
        self.horizontalLayout.addWidget(self.frame_2)

        self.retranslateUi(login_ui)
        QtCore.QMetaObject.connectSlotsByName(login_ui)

    def retranslateUi(self, login_ui):
        _translate = QtCore.QCoreApplication.translate
        login_ui.setWindowTitle(_translate("login_ui", "Form"))
        self.label_5.setText(_translate("login_ui", "气腔播散诊断系统登录"))
        self.user_name_lineEdit_3.setPlaceholderText(_translate("login_ui", "用户名"))
        self.password_lineEdit_3.setPlaceholderText(_translate("login_ui", "密码"))
        self.login_pushButton_2.setText(_translate("login_ui", "登录"))
import ui.image_rc

