# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 634)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 911, 581))
        self.frame.setStyleSheet("background-color: rgba(0, 85, 100,150);")
        self.frame.setObjectName("frame")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 200, 100, 100))
        self.pushButton_4.setStyleSheet("border-radius:50px;\n"
"background-color:rgba(0,255,255,255);\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 200, 100, 100))
        self.pushButton_3.setStyleSheet("border-radius:50px;\n"
"background-color:rgba(0,255,0,255);\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(790, 40, 50, 50))
        self.pushButton.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"border-image: url(:/icon/icon/关闭弹窗.svg);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(750, 40, 50, 50))
        self.pushButton_2.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"border-image: url(:/icon/icon/删除菜单.svg);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 26))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu = QtWidgets.QMenu(self.menu_File)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_1 = QtWidgets.QAction(MainWindow)
        self.action_1.setObjectName("action_1")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu_File.addAction(self.menu.menuAction())
        self.menu_File.addAction(self.action_1)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "批量上传"))
        self.pushButton_3.setText(_translate("MainWindow", "单张上传"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu.setTitle(_translate("MainWindow", "打开"))
        self.action_1.setText(_translate("MainWindow", "上传记录"))
        self.action_2.setText(_translate("MainWindow", "单张上传"))
        self.action_3.setText(_translate("MainWindow", "批量上传"))
import ui.image_rc
