# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_demo1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName("frmMain")
        frmMain.resize(1200, 680)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmMain.sizePolicy().hasHeightForWidth())
        frmMain.setSizePolicy(sizePolicy)
        frmMain.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(frmMain)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.loginWin = QtWidgets.QWidget(self.centralwidget)
        self.loginWin.setGeometry(QtCore.QRect(100, 130, 400, 400))
        self.loginWin.setStyleSheet("")
        self.loginWin.setObjectName("loginWin")
        self.okButton = QtWidgets.QToolButton(self.loginWin)
        self.okButton.setGeometry(QtCore.QRect(40, 280, 320, 40))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QToolButton(self.loginWin)
        self.cancelButton.setGeometry(QtCore.QRect(40, 330, 320, 40))
        self.cancelButton.setObjectName("cancelButton")
        self.widgetUser = QtWidgets.QWidget(self.loginWin)
        self.widgetUser.setGeometry(QtCore.QRect(40, 120, 320, 40))
        self.widgetUser.setObjectName("widgetUser")
        self.lineEditUser = QtWidgets.QLineEdit(self.widgetUser)
        self.lineEditUser.setGeometry(QtCore.QRect(50, 2, 270, 35))
        self.lineEditUser.setObjectName("lineEditUser")
        self.widgetPwd = QtWidgets.QWidget(self.loginWin)
        self.widgetPwd.setGeometry(QtCore.QRect(40, 200, 320, 40))
        self.widgetPwd.setObjectName("widgetPwd")
        self.lineEditPwd = QtWidgets.QLineEdit(self.widgetPwd)
        self.lineEditPwd.setGeometry(QtCore.QRect(50, 2, 270, 35))
        self.lineEditPwd.setObjectName("lineEditPwd")
        # frmMain.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmMain)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        _translate = QtCore.QCoreApplication.translate
        frmMain.setWindowTitle(_translate("frmMain", "系统登录"))
        self.okButton.setText(_translate("frmMain", "登录"))
        self.cancelButton.setText(_translate("frmMain", "取消"))
